// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20220516223620_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.model.Alquileres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("FechaAlquieler")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("clienteId")
                        .HasColumnType("int");

                    b.Property<int>("estadoId")
                        .HasColumnType("int");

                    b.Property<string>("isbnId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("clienteId");

                    b.HasIndex("estadoId");

                    b.HasIndex("isbnId");

                    b.ToTable("Alquileres");
                });

            modelBuilder.Entity("Domain.model.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Domain.model.EstadoDeAlquileres", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoId");

                    b.ToTable("EstadoDeAlquileres");

                    b.HasData(
                        new
                        {
                            EstadoId = 1,
                            Descripcion = "Reservado"
                        },
                        new
                        {
                            EstadoId = 2,
                            Descripcion = "Alquilado"
                        },
                        new
                        {
                            EstadoId = 3,
                            Descripcion = "Cancelado"
                        });
                });

            modelBuilder.Entity("Domain.model.Libros", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Edicion")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Editorial")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("ISBN");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            ISBN = "9788466357913",
                            Autor = "Elena Ferrante",
                            Edicion = "001",
                            Editorial = "Debolsillo",
                            Imagen = "https://images.cdn1.buscalibre.com/fit-in/360x360/e1/a9/e1a9cabdf6a6e77043d564ae91ce8f6a.jpg",
                            Stock = 6,
                            Titulo = "Saga dos Amigas"
                        },
                        new
                        {
                            ISBN = "9788418052187",
                            Autor = "Alejandro Jodorowsky",
                            Edicion = "001",
                            Editorial = "Reservoir Books",
                            Imagen = "https://images.cdn2.buscalibre.com/fit-in/360x360/15/05/15051197af8f0a016247e1cc176738b8.jpg",
                            Stock = 2,
                            Titulo = "La Casta de los Metabarones"
                        },
                        new
                        {
                            ISBN = "9786287544079",
                            Autor = "Gleen Black",
                            Edicion = "001",
                            Editorial = "Sin Fronteras Grupo Editorial",
                            Imagen = "https://images.cdn3.buscalibre.com/fit-in/360x360/9b/27/9b272c321c2616e64a855bf8c6034cbb.jpg",
                            Stock = 7,
                            Titulo = "BRATVA"
                        },
                        new
                        {
                            ISBN = "9786075277851",
                            Autor = "Robert Greene",
                            Edicion = "001",
                            Editorial = "Oceano",
                            Imagen = "https://images.cdn3.buscalibre.com/fit-in/360x360/8c/40/8c40d2433efdea2ef6c91cf2f16c1135.jpg",
                            Stock = 4,
                            Titulo = "El Arte de la Seduccion"
                        },
                        new
                        {
                            ISBN = "9788424653491",
                            Autor = "Miguel De Cervantes",
                            Edicion = "001",
                            Editorial = "La Galera",
                            Imagen = "https://images.cdn1.buscalibre.com/fit-in/360x360/a5/35/a5359eb612f3f5b42fe8addbc0950f53.jpg",
                            Stock = 3,
                            Titulo = "Don Quijote de la Mancha"
                        },
                        new
                        {
                            ISBN = "9789875809659",
                            Autor = "Dross",
                            Edicion = "001",
                            Editorial = "Booket",
                            Imagen = "https://images.cdn1.buscalibre.com/fit-in/360x360/93/1d/931d2a5a6c9ab4c117f34dd704c52749.jpg",
                            Stock = 10,
                            Titulo = "Luna de Pluton"
                        },
                        new
                        {
                            ISBN = "9789508701695",
                            Autor = "Dross",
                            Edicion = "001",
                            Editorial = "Martinez Roca",
                            Imagen = "https://images.cdn1.buscalibre.com/fit-in/360x360/a3/ad/a3ad3aa75860ff13996e6be80c3b0cbb.jpg",
                            Stock = 5,
                            Titulo = "Escape"
                        },
                        new
                        {
                            ISBN = "9789507301131",
                            Autor = "Dross",
                            Edicion = "001",
                            Editorial = "Temas De Hoy",
                            Imagen = "https://images.cdn2.buscalibre.com/fit-in/360x360/83/63/8363e7713727af1a04591376c1d9af50.jpg",
                            Stock = 30,
                            Titulo = "El Festival de la Blasfemia"
                        },
                        new
                        {
                            ISBN = "9789584282613",
                            Autor = "Dross",
                            Edicion = "001",
                            Editorial = "Grupo Planeta",
                            Imagen = "https://images.cdn1.buscalibre.com/fit-in/360x360/97/66/976684737c819ca0af8e67f75bf113ba.jpg",
                            Stock = 7,
                            Titulo = "El Libro Negro"
                        },
                        new
                        {
                            ISBN = "9875731994",
                            Autor = "Valentino E.",
                            Edicion = "001",
                            Editorial = "Sm",
                            Imagen = "https://images.cdn1.buscalibre.com/fit-in/360x360/cb/b7/cbb71b617b8030055f6d1c126154f08e.jpg",
                            Stock = 7,
                            Titulo = "Perros de Nadie"
                        },
                        new
                        {
                            ISBN = "9871093225",
                            Autor = "Robert Stevenson",
                            Edicion = "001",
                            Editorial = "Gradifco",
                            Imagen = "https://image.cdn0.buscalibre.com/2817664.__RS360x360__.jpg",
                            Stock = 9,
                            Titulo = "El diablo en la botella"
                        });
                });

            modelBuilder.Entity("Domain.model.Alquileres", b =>
                {
                    b.HasOne("Domain.model.Cliente", "Cliente")
                        .WithMany("Alquileres")
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.model.EstadoDeAlquileres", "Estado")
                        .WithMany("Alquileres")
                        .HasForeignKey("estadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.model.Libros", "Isbn")
                        .WithMany("Alquileres")
                        .HasForeignKey("isbnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estado");

                    b.Navigation("Isbn");
                });

            modelBuilder.Entity("Domain.model.Cliente", b =>
                {
                    b.Navigation("Alquileres");
                });

            modelBuilder.Entity("Domain.model.EstadoDeAlquileres", b =>
                {
                    b.Navigation("Alquileres");
                });

            modelBuilder.Entity("Domain.model.Libros", b =>
                {
                    b.Navigation("Alquileres");
                });
#pragma warning restore 612, 618
        }
    }
}
