// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Funcion", b =>
                {
                    b.Property<int>("FuncionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("FuncionId");

                    b.HasIndex("PeliculaId");

                    b.HasIndex("SalaId");

                    b.ToTable("Funciones");
                });

            modelBuilder.Entity("Domain.Entities.Pelicula", b =>
                {
                    b.Property<int>("PeliculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PeliculaId");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            PeliculaId = 1,
                            Poster = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/fast-and-furious-9-poster-1580411801.jpeg?crop=1xw:1xh;center,top&resize=980:*",
                            Sinopsis = "Dom Toretto tiene una vida tranquila fuera del radar, con Letty y su hijo, el pequeño Brian, pero saben que el peligro siempre acecha en su horizonte pacífico.",
                            Titulo = "Rápidos y furiosos 9",
                            Trailer = "https://www.youtube.com/watch?v=t3DpuQrBivU&ab_channel=TrailersInSpanish"
                        },
                        new
                        {
                            PeliculaId = 2,
                            Poster = "https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SL1183_.jpg",
                            Sinopsis = "A la deriva en el espacio sin comida ni agua, Tony Stark envía un mensaje a Pepper Potts cuando su suministro de oxígeno comienza a disminuir.",
                            Titulo = "Avengers EndGame",
                            Trailer = "https://www.youtube.com/watch?v=TcMBFSGVi1c&ab_channel=MarvelEntertainment"
                        },
                        new
                        {
                            PeliculaId = 3,
                            Poster = "https://es.web.img3.acsta.net/r_1920_1080/pictures/21/02/25/18/01/0475358.jpg",
                            Sinopsis = "La identidad de Spider-Man se revela a todos, y ya no puede separar su vida normal de su vida de superhéroe.",
                            Titulo = "Spiderman: No way home",
                            Trailer = "https://www.youtube.com/watch?v=rt-2cxAiPJk&ab_channel=SonyPicturesEntertainment"
                        },
                        new
                        {
                            PeliculaId = 4,
                            Poster = "https://pics.filmaffinity.com/sonic_the_hedgehog-730493692-large.jpg",
                            Sinopsis = "El mundo necesitaba un héroe, tenía un erizo. Impulsado con una velocidad increíble, Sonic abraza su nuevo hogar en la Tierra.",
                            Titulo = "Sonic the hedgehog",
                            Trailer = "https://www.youtube.com/watch?v=Xb3E8eWZ1mk&ab_channel=SensaCineTRAILERS"
                        },
                        new
                        {
                            PeliculaId = 5,
                            Poster = "https://static.wikia.nocookie.net/disney/images/c/cc/Luca_poster.jpg/revision/latest/scale-to-width-down/1000?cb=20210428135001&path-prefix=es",
                            Sinopsis = "Ambientada en una hermosa ciudad costera en la Riviera italiana, la película animada original es una historia sobre la mayoría de edad sobre un niño que experimenta un verano inolvidable lleno de helados, pasta e interminables paseos en scooter.",
                            Titulo = "Luca",
                            Trailer = "https://www.youtube.com/watch?v=EJk_Z-OasXc&ab_channel=SensaCineTRAILERS"
                        },
                        new
                        {
                            PeliculaId = 6,
                            Poster = "https://es.web.img3.acsta.net/r_1920_1080/pictures/20/12/28/10/26/5942577.jpg",
                            Sinopsis = "Jim es un ex infante de marina que vive una vida solitaria como ranchero a lo largo de la frontera entre Arizona y México. Pero su existencia pacífica pronto se derrumba cuando intenta proteger a un niño que huye de los miembros de un cartel vicioso.",
                            Titulo = "The marksman",
                            Trailer = "https://www.youtube.com/watch?v=lEBPNi4bEbc&ab_channel=MovieclipsTrailers"
                        },
                        new
                        {
                            PeliculaId = 7,
                            Poster = "https://www.imdb.com/title/tt6341832/mediaviewer/rm198951681/",
                            Sinopsis = "Una mujer se despierta en una cámara criogénica sin recordar cómo llegó allí, y debe encontrar una salida antes de quedarse sin aire.",
                            Titulo = "Oxygen",
                            Trailer = "https://www.youtube.com/watch?v=8IqXgZd-P98&ab_channel=Netflix"
                        },
                        new
                        {
                            PeliculaId = 8,
                            Poster = "https://imagenes.gatotv.com/categorias/peliculas/posters/infinite_2021.jpg",
                            Sinopsis = "Acosado por los recuerdos de lugares que nunca ha visitado, un hombre une fuerzas con un grupo de guerreros renacidos para evitar que un loco destruya el ciclo interminable de la vida y la reencarnación.",
                            Titulo = "Infinite",
                            Trailer = "https://www.youtube.com/watch?v=_WWEOCQGxSw&ab_channel=ONEMedia"
                        },
                        new
                        {
                            PeliculaId = 9,
                            Poster = "http://www.mubis.es/media/users/3724/287276/matrix-resurrection-nuevo-poster-original.jpg",
                            Sinopsis = "Plagado de extraños recuerdos, la vida de Neo da un giro inesperado cuando se encuentra de nuevo dentro de Matrix.",
                            Titulo = "Matrix 4",
                            Trailer = "https://www.youtube.com/watch?v=9ix7TUGVYIo&ab_channel=WarnerBros.Pictures"
                        },
                        new
                        {
                            PeliculaId = 10,
                            Poster = "https://pics.filmaffinity.com/tom_and_jerry-740894888-large.jpg",
                            Sinopsis = "Una rivalidad legendaria resurge cuando Jerry se muda al mejor hotel de la ciudad de Nueva York en vísperas de la boda del siglo, lo que obliga al desesperado planificador de eventos a contratar a Tom para deshacerse de él.",
                            Titulo = "Tom y jerry",
                            Trailer = "https://www.youtube.com/watch?v=ZJVb-IR1Jnw&ab_channel=WBKidsLatino"
                        },
                        new
                        {
                            PeliculaId = 11,
                            Poster = "https://pics.filmaffinity.com/godzilla_vs_kong-370227109-large.jpg",
                            Sinopsis = "Godzilla y Kong, dos de las fuerzas más poderosas de un planeta habitado por todo tipo de aterradoras criaturas, se enfrentan en un espectacular combate que sacude los cimientos de la humanidad.",
                            Titulo = "Godzilla vs. Kong",
                            Trailer = "https://www.youtube.com/watch?v=Kqg8zLgESyQ&ab_channel=WarnerBros.PicturesLatinoam%C3%A9rica"
                        },
                        new
                        {
                            PeliculaId = 12,
                            Poster = "https://static.wikia.nocookie.net/doblaje/images/5/53/E3XjApsWQAo7LrH.jpeg/revision/latest?cb=20210623234126&path-prefix=es",
                            Sinopsis = "Durante un viaje a los estudios de Warner Bros., la superestrella de la NBA LeBron James y su hijo Dom quedan atrapados accidentalmente en un mundo que contiene todas las historias y personajes de Warner",
                            Titulo = "Space Jam: una nueva era",
                            Trailer = "https://www.youtube.com/watch?v=8GltZA7F7-M&ab_channel=WarnerBros.PicturesLatinoam%C3%A9rica"
                        },
                        new
                        {
                            PeliculaId = 13,
                            Poster = "https://pics.filmaffinity.com/paw_patrol_the_movie-626479283-large.jpg",
                            Sinopsis = "La Patrulla Canina está en racha. Cuando Humdinger, su mayor rival, se convierte en alcalde de la cercana Ciudad Aventura y empieza a causar estragos, Ryder y los heroicos cachorros se ponen en marcha para enfrentarse a este nuevo desafío.",
                            Titulo = "La Patrulla Canina: La película",
                            Trailer = "https://www.youtube.com/watch?v=ABjdw_caRsQ&ab_channel=PARAMOUNTPICTURESM%C3%89XICO"
                        },
                        new
                        {
                            PeliculaId = 14,
                            Poster = "https://pics.filmaffinity.com/nobody-390795243-large.jpg",
                            Sinopsis = "Hutch Mansell (Bob Odenkirk) es un hombre de familia corriente. Una noche unos ladrones entran a su casa y él renuncia a defenderse y defender a su familia con el fin de evitar complicaciones.",
                            Titulo = "Nadie",
                            Trailer = "https://www.youtube.com/watch?v=Mzrib73dVbc&ab_channel=UniversalSpain"
                        },
                        new
                        {
                            PeliculaId = 15,
                            Poster = "https://pics.filmaffinity.com/the_unholy-403969644-large.jpg",
                            Sinopsis = "Un periodista en horas bajas descubre una serie de aparentes milagros de una joven que dice haber sido visitada por la Virgen María, milagros acaecidos en un pequeño pueblo de Nueva Inglaterra.",
                            Titulo = "Ruega por nosotros",
                            Trailer = "https://www.youtube.com/watch?v=a_BYIlWcbVg&ab_channel=SonyPicturesEspa%C3%B1a"
                        },
                        new
                        {
                            PeliculaId = 16,
                            Poster = "https://pics.filmaffinity.com/cato-646607409-large.jpg",
                            Sinopsis = "Cato, un joven del conurbano bonaerense, está a punto de convertirse en estrella de trap cuando una tragedia familiar parece poner fin a todos sus sueños y ambiciones.",
                            Titulo = "Cato",
                            Trailer = "https://www.youtube.com/watch?v=GDR_scpOHMI&ab_channel=Patagonik"
                        },
                        new
                        {
                            PeliculaId = 17,
                            Poster = "https://image.tmdb.org/t/p/original//hKZHk6I1p58ZeXbwjQok7DSWfZ.jpg",
                            Sinopsis = "Argentina, años setenta. Una joven desesperada recurre a una clínica que hace abortos clandestinos.",
                            Titulo = "El Apego",
                            Trailer = "https://www.youtube.com/watch?v=80P35D4vyHg&ab_channel=EL%C3%9ALTIMOBLOGALAIZQUIERDA"
                        },
                        new
                        {
                            PeliculaId = 18,
                            Poster = "https://images.clarin.com/2021/04/16/el-primer-afiche-que-se___8xbNrbH6m_720x0__1.jpg",
                            Sinopsis = "Los Eternos son una raza de seres inmortales con poderes sobrehumanos que han vivido en secreto en la Tierra durante miles de años. Aunque nunca han intervenido, ahora una amenaza se cierne sobre la humanidad.",
                            Titulo = "Eternals",
                            Trailer = "https://www.youtube.com/watch?v=v1EkoQV4g5c&ab_channel=MarvelLatinoam%C3%A9ricaOficial"
                        },
                        new
                        {
                            PeliculaId = 19,
                            Poster = "https://static.cinemarkhoyts.com.ar/Images/Posters/1fa377f4d4d78239363a228dd91ea241.jpg?v=01112021",
                            Sinopsis = "Chernobyl es el primer largometraje ruso importante sobre las consecuencias de la explosión en la central nuclear de Chernobyl, cuando cientos de personas sacrificaron sus vidas para limpiar el lugar de la catástrofe.",
                            Titulo = "Chernóbil: La Película",
                            Trailer = "https://www.youtube.com/watch?v=9DkXQM3eR8I&ab_channel=TrailersInSpanish"
                        },
                        new
                        {
                            PeliculaId = 20,
                            Poster = "https://www.multiplex.com.ar/wp-content/uploads/2021/09/venom-carnage-liberado.jpg",
                            Sinopsis = "Regresa Eddie Brock y su Venom. Que en esta oportunidad se reencontrará con Cletus Cassady,el enemigo más sangriento de la historia de Spiderman a quién se lo conoce como “Carnage”.",
                            Titulo = "Venom: Carnage Liberado",
                            Trailer = "https://www.youtube.com/watch?v=F4Ygcigj0Gk&ab_channel=SonyPicturesArgentina"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sala", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.HasKey("SalaId");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            SalaId = 1,
                            Capacidad = 5
                        },
                        new
                        {
                            SalaId = 2,
                            Capacidad = 15
                        },
                        new
                        {
                            SalaId = 3,
                            Capacidad = 35
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FuncionId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TicketId", "FuncionId");

                    b.HasIndex("FuncionId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Funcion", b =>
                {
                    b.HasOne("Domain.Entities.Pelicula", "Peliculas")
                        .WithMany("Funciones")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sala", "Salas")
                        .WithMany("Funciones")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peliculas");

                    b.Navigation("Salas");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.Funcion", "Funciones")
                        .WithMany("Tickets")
                        .HasForeignKey("FuncionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("Domain.Entities.Funcion", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Pelicula", b =>
                {
                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("Domain.Entities.Sala", b =>
                {
                    b.Navigation("Funciones");
                });
#pragma warning restore 612, 618
        }
    }
}
